# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release

on:
  push:
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    uses: ./.github/workflows/tests.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: test

  publish:
    name: Upload release to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: test-release
      url: ${{ vars.RELEASE_URL }}
    permissions:
      id-token: write
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ vars.RELEASE_REPOSITORY_URL }}